model:
    name: 'SelfSupModel'
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    test:
        dataset: ['KITTI']
        path: ['/home/seok436/data/datasets/KITTI_raw/']
        split: ['data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']
save:
    folder: '/home/seok436/data/eval_save'
    depth:
        rgb: True
        viz: True
        npz: True
        png: True
