arch:
    max_epochs: 50
checkpoint:
    filepath: '/home/seok436/data/md_model/'
    save_top_k: -1
model:
    name: 'SelfSupModel'
    checkpoint_path: '/home/seok436/data/md_model/ResNet18_MR_selfsup_D.ckpt'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.000001
        pose:
            lr: 0.000001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        min_depth: 0.0
        max_depth: 200.0
datasets:
    augmentation:
        image_shape: (384, 640)
    train:
        batch_size: 18
        dataset: ['Image']
        path: ['/home/seok436/data/nextchipDB_SSL/crop/v1+/T_0001/']
        split: ['{:010}']
        repeat: [2]
    validation:
        dataset: ['Image']
        path: ['/home/seok436/data/nextchipDB_SSL/crop/v1+/T_0002/']
        split: ['{:010}']
    test:
        dataset: ['Image']
        path: ['/home/seok436/data/nextchipDB_SSL/crop/v1+/T_0003/']
        split: ['{:010}']
