arch:
    max_epochs: 30
checkpoint:
    filepath: '/home/seok436/data/md_model/NCDB/DepthResNet/18/1280x720/'
    save_top_k: -1
model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 12
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (720, 1280)
    train:
        batch_size: 8
        dataset: ['Image']
        path: ['/home/seok436/data/nextchipDB_SSL/crop/TP_0001_v3/']
        split: ['{:010}']
    validation:
        dataset: ['Image']
        path: ['/home/seok436/data/nextchipDB_SSL/crop/TP_0002_v3/']
        split: ['{:010}']
    test:
        dataset: ['Image']
        path: ['/home/seok436/data/nextchipDB_SSL/crop/TP_0003_v3/']
        split: ['{:010}']