arch:
    max_epochs: 30
checkpoint:
    filepath: '/home/seok436/data/md_model/apache5_rearview/DepthrResDNet/pt_v4_intrinsic_original'
    save_top_k: -1
model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 14
        gamma: 0.5
    depth_net:
        name: 'DepthResDNet'
        version: '18np'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (384, 640)
    train:
        batch_size: 18
        dataset: ['Image']
        path: ['/home/seok436/data/A5_v4_rearview/A5_0001_rearview/']
        split: ['{:010}']
        repeat: [1]
    validation:
        dataset: ['Image']
        path: ['/home/seok436/data/A5_v4_rearview/A5_0002_rearview/']
        split: ['{:010}']
    test:
        dataset: ['Image']
        path: ['/home/seok436/data/A5_v4_rearview/A5_0003_rearview/']
        split: ['{:010}']
