arch:
    max_epochs: 60
checkpoint:
    filepath: '/home/seok436/data/md_model/'
    save_top_k: -1
model:
    name: 'SelfSupModel'
    checkpoint_path: '/home/seok436/data/md_model/ResNet18_MR_selfsup_K.ckpt'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.00002
        pose:
            lr: 0.00002
    scheduler:
        name: 'StepLR'
        step_size: 20
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 30
        dataset: ['Image']
        path: ['/home/seok436/data/nextchipDB_SSL/T_0001_back/']
        split: ['{:010}']
        repeat: [4]
    validation:
        dataset: ['Image']
        path: ['/home/seok436/data/nextchipDB_SSL/T_0002_back/']
        split: ['{:010}']
    test:
        dataset: ['Image']
        path: ['/home/seok436/data/nextchipDB_SSL/T_0003_back/']
        split: ['{:010}']
