arch:
    max_epochs: 20
checkpoint:
    filepath: '/home/seok436/data/md_model/A5_v5_rearview_ray/'
    save_top_k: -1
model:
    name: 'GenericSelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 12
        gamma: 0.5
    depth_net:
        name: 'RaySurfaceResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 320)
    train:
        batch_size: 1
        dataset: ['Image']
        path: ['/home/seok436/data/A5_v5_rearview/A5_0001_rearview/']
        split: ['{:010}']
        repeat: [1]
    validation:
        dataset: ['Image']
        path: ['/home/seok436/data/A5_v5_rearview/A5_0002_rearview/']
        split: ['{:010}']
    test:
        dataset: ['Image']
        path: ['/home/seok436/data/A5_v5_rearview/A5_0003_rearview/']
        split: ['{:010}']
