arch:
    max_epochs: 50
checkpoint:
<<<<<<< HEAD
    filepath: '/home/seok436/data/md_model/kitti/DepthRexNet/18/640_384/DepthRexNet_ImageNet_pt_channel_reduction/8_8_16_16'
=======
    filepath: '/home/seok436/data/md_model/kitti/DepthRexNet/18/640_384/DepthReXNet_pt/72_80_96_112'
>>>>>>> c05589404f1f6e299e24fb74314c1f5f5fdf7c6c
    save_top_k: -1
model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 14
        gamma: 0.5
    depth_net:
        name: 'DepthReXNet'
<<<<<<< HEAD
        version: '18no'
=======
        version: '18np'
>>>>>>> c05589404f1f6e299e24fb74314c1f5f5fdf7c6c
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (384, 640)
    train:
<<<<<<< HEAD
        batch_size: 16
=======
        batch_size: 18
>>>>>>> c05589404f1f6e299e24fb74314c1f5f5fdf7c6c
        dataset: ['KITTI']
        path: ['/home/seok436/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_zhou_files.txt']
        depth_type: ['velodyne']
        repeat: [1]
    validation:
        dataset: ['KITTI']
        path: ['/home/seok436/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_val_files.txt',
                'data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['/home/seok436/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']