arch:
    max_epochs: 50
checkpoint:
    filepath: '/home/seok436/data/md_model/A5_frontview/repVGG/intrinsics_1000'
    save_top_k: -1
model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 14
        gamma: 0.5
    depth_net:
        name: 'DepthRepVGGNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (384, 640)
    train:
        batch_size: 20
        dataset: ['Image']
        path: ['/home/seok436/data/A5_v1_frontview/A5T_0001/']
        split: ['{:010}']
        repeat: [1]
    validation:
        dataset: ['Image']
        path: ['/home/seok436/data/A5_v1_frontview/A5T_0002/']
        split: ['{:010}']
    test:
        dataset: ['Image']
        path: ['/home/seok436/data/A5_v1_frontview/A5T_0003/']
        split: ['{:010}']